services:
  tasvc:
    image: biandayu/tasvc:0.0.1
    volumes:
      - models:/models
      - type: bind
        source: $PWD/.env.override
        target: /app/.env
      - type: bind
        source: $PWD/logging_config_console.yaml
        target: /app/logging_config.yaml
    ports:
      - 8000:8000

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
    volumes:
      - qdrant-data:/qdrant/sotrage
      - type: bind
        source: $HOME/qdrant/config/custom_config.yaml
        target: /qdrant/config/production.yaml

volumes:
  qdrant-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/qdrant/storage"

  models:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/sentencetransformer"